### ISSUE TITLE
Renaming variables

### ISSUE THREAD

**Issue by ChRen95** [pyroll-project/pyroll-ludwik-flow-stress#2]
Please consider renaming the variables `kf0 , del_kf1` etc.
Give them more representative names like `baseFlowStress` or something else. 
Otherwise people who haven't read the exact publication might have difficulties to understand what this plugin is doing.

**Comment by okolekar** [comment]
renamed kf0 as baseYieldStress
and delkf as hardeningModulus

**Comment by okolekar** [comment]
In swift approach the variables are named as follows:
kf1 as hardeningRate
and phi0 as base strain 
These names are given as per the description in the paper "PLASTIC INSTABILITY UNDER PLANE STRESS" by H.W. Swift
